// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_cookie_oauth_login_auth_cookie_login_post = {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
};

export type ErrorModel = {
	detail:
		| string
		| {
				[key: string]: string;
		  };
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type OAuth2AuthorizeResponse = {
	authorization_url: string;
};

export type UserRead = {
	id: string;
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	is_verified?: boolean;
};

export type UserUpdate = {
	password?: string | null;
	email?: string | null;
	is_active?: boolean | null;
	is_superuser?: boolean | null;
	is_verified?: boolean | null;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type AuthCookieOauthLoginAuthCookieLoginPostData = {
	formData: Body_auth_cookie_oauth_login_auth_cookie_login_post;
};

export type AuthCookieOauthLoginAuthCookieLoginPostResponse =
	| unknown
	| undefined;

export type AuthCookieOauthLogoutAuthCookieLogoutPostResponse =
	| unknown
	| undefined;

export type OauthGoogleCookieOauthAuthorizeAuthGoogleAuthorizeGetData = {
	scopes?: Array<string>;
};

export type OauthGoogleCookieOauthAuthorizeAuthGoogleAuthorizeGetResponse =
	OAuth2AuthorizeResponse;

export type OauthGoogleCookieOauthCallbackAuthGoogleCallbackGetData = {
	code?: string | null;
	codeVerifier?: string | null;
	error?: string | null;
	state?: string | null;
};

export type OauthGoogleCookieOauthCallbackAuthGoogleCallbackGetResponse =
	unknown;

export type AuthenticatedRouteAuthenticatedRouteGetResponse = unknown;

export type UsersCurrentUserUsersMeGetResponse = UserRead;

export type UsersPatchCurrentUserUsersMePatchData = {
	requestBody: UserUpdate;
};

export type UsersPatchCurrentUserUsersMePatchResponse = UserRead;

export type UsersUserUsersIdGetData = {
	id: string;
};

export type UsersUserUsersIdGetResponse = UserRead;

export type UsersPatchUserUsersIdPatchData = {
	id: string;
	requestBody: UserUpdate;
};

export type UsersPatchUserUsersIdPatchResponse = UserRead;

export type UsersDeleteUserUsersIdDeleteData = {
	id: string;
};

export type UsersDeleteUserUsersIdDeleteResponse = undefined;
