// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_cookie_login_api_v1_auth_cookie_login_post = {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
};

export type ErrorModel = {
	detail:
		| string
		| {
				[key: string]: string;
		  };
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type OAuth2AuthorizeResponse = {
	authorization_url: string;
};

export type UserRead = {
	id: string;
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	is_verified?: boolean;
};

export type UserUpdate = {
	password?: string | null;
	email?: string | null;
	is_active?: boolean | null;
	is_superuser?: boolean | null;
	is_verified?: boolean | null;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type AuthCookieLoginApiV1AuthCookieLoginPostData = {
	formData: Body_auth_cookie_login_api_v1_auth_cookie_login_post;
};

export type AuthCookieLoginApiV1AuthCookieLoginPostResponse = unknown | void;

export type AuthCookieLogoutApiV1AuthCookieLogoutPostResponse = unknown | void;

export type OauthGoogleCookieOauthAuthorizeApiV1AuthGoogleAuthorizeGetData = {
	scopes?: Array<string>;
};

export type OauthGoogleCookieOauthAuthorizeApiV1AuthGoogleAuthorizeGetResponse =
	OAuth2AuthorizeResponse;

export type OauthGoogleCookieOauthCallbackApiV1AuthGoogleCallbackGetData = {
	code?: string | null;
	codeVerifier?: string | null;
	error?: string | null;
	state?: string | null;
};

export type OauthGoogleCookieOauthCallbackApiV1AuthGoogleCallbackGetResponse =
	unknown;

export type AuthenticatedRouteApiV1AuthenticatedRouteGetResponse = unknown;

export type UsersCurrentUserApiV1UsersMeGetResponse = UserRead;

export type UsersPatchCurrentUserApiV1UsersMePatchData = {
	requestBody: UserUpdate;
};

export type UsersPatchCurrentUserApiV1UsersMePatchResponse = UserRead;

export type UsersUserApiV1UsersIdGetData = {
	id: string;
};

export type UsersUserApiV1UsersIdGetResponse = UserRead;

export type UsersPatchUserApiV1UsersIdPatchData = {
	id: string;
	requestBody: UserUpdate;
};

export type UsersPatchUserApiV1UsersIdPatchResponse = UserRead;

export type UsersDeleteUserApiV1UsersIdDeleteData = {
	id: string;
};

export type UsersDeleteUserApiV1UsersIdDeleteResponse = void;
